# .goreleaser.yml
# GoReleaser configuration for advanced release management
# Install: brew install goreleaser
# Usage: goreleaser release --clean

version: 2

project_name: kconduit

before:
  hooks:
    - go mod tidy
    - go mod verify

builds:
  - id: kconduit
    main: ./cmd/kconduit
    binary: kconduit
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.GitCommit={{.Commit}}
      - -X main.BuildTime={{.Date}}
      - -X main.builtBy=goreleaser

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - { goos: windows, format: zip }
    files:
      - LICENSE*
      - README*
      - CHANGELOG*

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^build:'
      - '^style:'
      - '^refactor:'
      - '^Merge pull request'
      - '^Merge branch'
  groups:
    - title: 'Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug Fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: 'Performance Improvements'
      regexp: "^.*perf[(\\w)]*:+.*$"
      order: 2
    - title: 'Other changes'
      order: 999

dockers:
  - image_templates:
      - "ghcr.io/axonops/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/axonops/{{ .ProjectName }}:latest-amd64"
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
  
  - image_templates:
      - "ghcr.io/axonops/{{ .ProjectName }}:{{ .Version }}-arm64"
      - "ghcr.io/axonops/{{ .ProjectName }}:latest-arm64"
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
    goarch: arm64

docker_manifests:
  - name_template: "ghcr.io/axonops/{{ .ProjectName }}:{{ .Version }}"
    image_templates:
      - "ghcr.io/axonops/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/axonops/{{ .ProjectName }}:{{ .Version }}-arm64"
  
  - name_template: "ghcr.io/axonops/{{ .ProjectName }}:latest"
    image_templates:
      - "ghcr.io/axonops/{{ .ProjectName }}:latest-amd64"
      - "ghcr.io/axonops/{{ .ProjectName }}:latest-arm64"

brews:
  - repository:
      owner: "axonops"
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/axonops/kconduit"
    description: "Powerful terminal UI for Apache Kafka management"
    license: "Apache-2.0"
    test: |
      system "#{bin}/kconduit", "--version"
    install: |
      bin.install "kconduit"

nfpms:
  - id: packages
    package_name: kconduit
    vendor: Digitalis.IO
    homepage: "https://github.com/axonops/kconduit"
    maintainer: "Digitalis <info@digitalis.io>"
    description: "Powerful terminal UI for Apache Kafka management"
    license: Apache-2.0
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin
    contents:
      - src: ./LICENSE
        dst: /usr/share/licenses/kconduit/LICENSE
      - src: ./README.md
        dst: /usr/share/doc/kconduit/README.md

release:
  github:
    owner: "axonops"
    name: "{{ .ProjectName }}"
  draft: false
  prerelease: auto
  mode: replace
  name_template: "v{{.Version}}"
  disable: false